openapi: 3.0.1
info:
  title: Coldchain-Beta
  description: Coldchain-Beta
  version: 0.2.0
servers:
- url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
paths:
  /v12/coldchain/vaccinebox/claimCount:
    get:
      description: API returns the total number of claims submitted
      operationId: v12ColdchainVaccineboxClaimCountGET
      responses:
        "200":
          description: Total number of claims
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              examples:
                "0":
                  value: '{"ClaimCount":8}'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/shipment/graphInfo:
    get:
      description: API used to retrieve geotag data(Current location).
      operationId: v12ColdchainShipmentGraphInfoGET
      responses:
        "200":
          description: Retrieves geotag data for a shipment
          content:
            application/json:
              schema:
                type: object
                properties: {}
                example: {}
                x-content-type: application/json
              examples:
                "0":
                  value: '[{"ShipmentId":"S-22","TemperatureAlert":1,"Latitude":"16.9716°
                    S","Longitude":"72.5946° W","XAxis":-16.9716,"YAxis":-72.5946,"Location":"NJ"},{"ShipmentId":"S-12","TemperatureAlert":0,"Latitude":"12.9716°
                    N","Longitude":"77.5946° E","XAxis":12.9716,"YAxis":77.5946,"Location":"CA"},{"ShipmentId":"S-09","TemperatureAlert":0,"Latitude":"12.9716°
                    N","Longitude":"77.5946° E","XAxis":12.9716,"YAxis":77.5946,"Location":"CA"},{"ShipmentId":"S-08","TemperatureAlert":0,"Latitude":"12.9716°
                    N","Longitude":"77.5946° E","XAxis":12.9716,"YAxis":77.5946,"Location":"CA"},{"ShipmentId":"S-01","TemperatureAlert":0,"Latitude":"40.75°
                    N","Longitude":"74.37° W","XAxis":40.75,"YAxis":-74.37,"Location":"Ambrose,NY"},{"ShipmentId":"S-16","TemperatureAlert":12,"Latitude":"14.9716°
                    S","Longitude":"69.5946° W","XAxis":-14.9716,"YAxis":-69.5946,"Location":"NJ"},{"ShipmentId":"S-07","TemperatureAlert":23,"Latitude":"32.42°
                    N","Longitude":"99.68° W","XAxis":32.42,"YAxis":-99.68,"Location":"Abilene,TX"},{"ShipmentId":"S-20","TemperatureAlert":57,"Latitude":"14.9716° S","Longitude":"69.5946° W","XAxis":-14.9716,"YAxis":-69.5946,"Location":"NJ"},{"ShipmentId":"S-05","TemperatureAlert":39,"Latitude":"36.45°
                    N","Longitude":"73.57° W","XAxis":36.45,"YAxis":-73.57,"Location":"Atlantic
                    Cty,NJ"},{"ShipmentId":"S-02","TemperatureAlert":3,"Latitude":"39.45°
                    N","Longitude":"74.57° W","XAxis":39.45,"YAxis":-74.57,"Location":"Atlantic
                    Cty,NJ"},{"ShipmentId":"S-03","TemperatureAlert":0,"Latitude":"32.42°
                    N","Longitude":"99.68° W","XAxis":32.42,"YAxis":-99.68,"Location":"Abilene,TX"},{"ShipmentId":"S-04","TemperatureAlert":4,"Latitude":"12.9716°
                    N","Longitude":"77.5946° E","XAxis":12.9716,"YAxis":77.5946,"Location":"Abilene,TX"},{"ShipmentId":"S-06","TemperatureAlert":343,"Latitude":"41.74°
                    N","Longitude":"73.36° W","XAxis":41.74,"YAxis":-73.36,"Location":"Ambrose,NY"},{"ShipmentId":"S-11","TemperatureAlert":0},{"ShipmentId":"S-15","TemperatureAlert":7,"Latitude":"12.9716°
                    N","Longitude":"77.5946° E","XAxis":12.9716,"YAxis":77.5946,"Location":"CA"},{"ShipmentId":"S-13","TemperatureAlert":0,"Latitude":"12.9716°
                    N","Longitude":"77.5946° E","XAxis":12.9716,"YAxis":77.5946,"Location":"CA"},{"ShipmentId":"S-14","TemperatureAlert":1,"Latitude":"14.9716°
                    S","Longitude":"69.5946° W","XAxis":-14.9716,"YAxis":-69.5946,"Location":"NJ"},{"ShipmentId":"S-21","TemperatureAlert":1,"Latitude":"14.9716°
                    S","Longitude":"69.5946° W","XAxis":-14.9716,"YAxis":-69.5946,"Location":"NJ"}]'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/claimRequest:
    post:
      description: API for submitting claim request
      operationId: v12ColdchainVaccineboxClaimRequestPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
            examples:
              "0":
                value: "\t\t{\n\t\t\t\"shipmentId\": \"S-22\",\n\t\t\t\"policyId\"\
                  : \"P-22\"\n\t\t}"
      responses:
        "200":
          description: API for submitting claim request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
              examples:
                "0":
                  value: '{"ShipmentId":"S-22","ClaimId":"CLM-P-22","response":"New
                    claim request initiated"}'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/shipment/provenance/S-22:
    get:
      description: API to gett shipment movement tracker information
      operationId: v12ColdchainShipmentProvenanceS_22GET
      responses:
        "200":
          description: Shipment movement tracker
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
              examples:
                "0":
                  value: '{"OriginLeg":{"ShipmentId":"S-22","BatchId":"LNQEOL2RUONIWYJSGWCJZA","DeviceId":"D-22","Origin":"Insurer-1","originRole":"Manufacturer","originAddress":"1567
                    TX  302, Dallas, TX 75204-2426, US","destination":"Wholesaler-1","destinationRole":"Wholesaler","destinationAddress":"Wholesaler-1,
                    Victoria Street, DH","Logistics":"Logistics-1"},"Childlegs":[{"RetailShipmentId":"RS-22","RetailQuantity":50,"Origin":"Wholesaler-1","originRole":"Wholesaler","originAddress":"Wholesaler1,121
                    Highway 45","destination":"Retailer-1","destinationRole":"Retailer","destinationAddress":"Retailer-1,
                    NY","Logistics":"ABC Logistics","MasterShipmentId":"S-22"}]}'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/report/sensorDataAuditTrail/S-22:
    get:
      description: API returns sensor data audit trail
      operationId: v12ColdchainVaccineboxReportSensorDataAuditTrailS_22GET
      responses:
        "200":
          description: Sensor data audit trail for specified shipment
          content:
            application/json:
              schema:
                type: object
                properties: {}
                example: {}
                x-content-type: application/json
              examples:
                "0":
                  value: '[{"ShipmentID":"S-22","DateTime":"2020-11-03T05:44:01.890Z","CurrentOwner":"Wholesaler-1","CurrentRole":"Wholesaler","deviceId":"D-22","Temperature":-6,"Humidity":55,"Hash":"voJ6wc4h/gXDJgqBx2Xk16LL0iKWFXHwtkOoRe1gGFY="}]'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/insurance/shipmentData:
    get:
      description: API returns shipment with claims submitted
      operationId: v12ColdchainInsuranceShipmentDataGET
      responses:
        "200":
          description: Shipment with claims
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/alert/sensorData:
    get:
      description: API to send alert to users
      operationId: v12ColdchainVaccineboxAlertSensorDataGET
      responses:
        "200":
          description: Aert notification
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
              examples:
                "0":
                  value: '{"shipmentId":"S-22","deviceId":"D-22","temperature":-6,"txTime":"2020-11-03T05:44:01.890Z"}'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/retailShipment:
    post:
      description: API to submit retail shipment (Wholesaler to Retailer)
      operationId: v12ColdchainVaccineboxRetailShipmentPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_1'
            examples:
              "0":
                value: "\t\t\t{\n\t\t\t\t\"RetailShipmentId\": \"RS-22\",\n\t\t\t\t\
                  \"RetailQuantity\": 50,\n\t\t\t\t\"WayBill\": {\n\t\t\t\t\t\"origin\"\
                  : \"Wholesaler-1\",\n\t\t\t\t\t\"originRole\": \"Wholesaler\",\n\
                  \t\t\t\t\t\"originAddress\":\"Wholesaler1,121 Highway 45\",\t\n\t\
                  \t\t\t\t\"destination\": \"Retailer-1\",\n\t\t\t\t\t\"destinationRole\"\
                  : \"Retailer\",\n\t\t\t\t\t\"destinationAddress\": \"Retailer-1,\
                  \ NY\",\n\t\t\t\t\t\"logistics\": \"ABC Logistics\"\t\n\t\t\t\t\
                  },\n\t\t\t    \"MasterShipmentId\": \"S-22\"                \t\t\
                  \t\t\n\t\t\t}"
      responses:
        "200":
          description: Wholesaler to Retailer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
              examples:
                "0":
                  value: '{"RetailShipmentId":"RS-22","RetailQuantity":50,"status":"In-Transit","shippingDate":"2020-11-03T05:42:42+0000","WayBill":{"origin":"Wholesaler-1","originRole":"Wholesaler","originAddress":"Wholesaler1,121
                    Highway 45","destination":"Retailer-1","destinationRole":"Retailer","destinationAddress":"Retailer-1,
                    NY","logistics":"ABC Logistics"}}'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/events/shipmentMovements/S-22:
    get:
      description: API shows shipment movement data
      operationId: v12ColdchainVaccineboxEventsShipmentMovementsS_22GET
      responses:
        "200":
          description: API shows shipment movement data
          content:
            application/json:
              schema:
                type: object
                properties: {}
                example: {}
                x-content-type: application/json
              examples:
                "0":
                  value: '[{"ShipmentID":"S-22","Status":"In-Transit","manufacturer":"ABC","VaccineName":"Covax-22","CurrentOwner":"Wholesaler","shipmentTrackerEvents":[{"eventType":"SHIPMENT_RECEIVED","eventDesc":"Received","eventOwner":"Wholesaler-1","eventRole":"Wholesaler","sensorCondition":"Active,
                    normal readings","eventDate":"2020-11-03T05:41:53+0000","nextRole":"NA"},{"eventType":"SHIPMENT_DELIVERED","eventDesc":"Pending
                    Confirmation","eventOwner":"Logistics-1","eventRole":"Logistics","sensorCondition":"Active,
                    normal readings","eventDate":"2020-11-03T05:40:17+0000","nextRole":"Wholesaler"},{"eventType":"SHIPMENT_RECEIVED","eventDesc":"Received","eventOwner":"Logistics-1","eventRole":"Logistics","sensorCondition":"Active,
                    normal readings","eventDate":"2020-11-03T05:39:24+0000","nextRole":"Wholesaler"},{"eventType":"SHIPMENT_DELIVERED","eventDesc":"Pending
                    Confirmation","eventOwner":"Insurer-1","eventRole":"Manufacturer","sensorCondition":"Active,
                    normal readings","eventDate":"2020-11-03T05:38:25+0000","nextRole":"Logistics"},{"eventOwner":"ABC
                    Manufacturer","eventRole":"Manufacturer","eventType":"SHIPPING","eventDesc":"Left
                    Facility","sensorCondition":"Active, normal readings","eventDate":"2020-11-03T05:36:57+0000"}]}]'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/shipment:
    post:
      description: API for creating new shipment
      operationId: v12ColdchainVaccineboxShipmentPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_2'
            examples:
              "0":
                value: "\t\t\t{\n\t\t\t\t\"vaccineName\": \"Covax-22\",\n\t\t\t\t\"\
                  shipmentId\": \"S-22\",\n\t\t\t\t\"quantity\": \"300\",\n\t\t\t\t\
                  \"policyId\": \"P-21\",\n\t\t\t\t\"insurer\": \"Insurer-1\",\n\t\
                  \t\t\t\"insuredValue\": 1000,\n\t\t\t\t\"wayBill\": {\n\t\t\t\t\t\
                  \"origin\": \"Insurer-1\",\n\t\t\t\t\t\"originRole\": \"Manufacturer\"\
                  ,\n\t\t\t\t\t\"originAddress\":\"1567 TX  302, Dallas, TX 75204-2426,\
                  \ US\",\t\n\t\t\t\t\t\"destination\": \"Wholesaler-1\",\n\t\t\t\t\
                  \t\"destinationRole\": \"Wholesaler\",\n\t\t\t\t\t\"destinationAddress\"\
                  : \"Wholesaler-1, Victoria Street, DH\",\n\t\t\t\t\t\"logistics\"\
                  : \"Logistics-1\"\t\n\t\t\t\t}\t\t\t\t\n\t\t\t}"
      responses:
        "200":
          description: New shipment creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
              examples:
                "0":
                  value: '{"vaccineName":"Covax-22","shipmentId":"S-22","batchId":"LNQEOL2RUONIWYJSGWCJZA","quantity":"300","manufacturer":"ABC
                    Manufacturer","currentRole":"Manufacturer","currentOwner":"ABC
                    Manufacturer","status":"In-Transit","temperatureExcursion":0,"humidityRangeViolation":0,"policyId":"P-21","insurer":"Insurer-1","insuredValue":1000,"shipmentTrackerEvent":[{"eventOwner":"ABC
                    Manufacturer","eventRole":"Manufacturer","eventType":"SHIPPING","eventDesc":"Left
                    Facility","sensorCondition":"Active, normal readings","eventDate":"2020-11-03T05:36:57+0000"}],"wayBill":{"origin":"Insurer-1","originRole":"Manufacturer","originAddress":"1567
                    TX  302, Dallas, TX 75204-2426, US","destination":"Wholesaler-1","destinationRole":"Wholesaler","destinationAddress":"Wholesaler-1,
                    Victoria Street, DH","logistics":"Logistics-1"},"currentGeoLocation":{"latitude":"12.9716°
                    N","xaxis":12.9716,"longitude":"77.5946° E","yaxis":77.5946,"location":"CA"}}'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/recentClaims:
    get:
      description: API returns recent claims information
      operationId: v12ColdchainVaccineboxRecentClaimsGET
      responses:
        "200":
          description: Recent claims data
          content:
            application/json:
              schema:
                type: object
                properties: {}
                example: {}
                x-content-type: application/json
              examples:
                "0":
                  value: '[{"ShipmentID":"S-22","ShippingDate":"2020-11-03T05:36:57+0000","Insurer":"Insurer-1","PolicyId":"P-21","ClaimID":"CLM-P-22","ClaimRequestDate":"2020-11-03T05:44:38+0000","ClaimStatus":"New
                    claim request","Manufacturer":"ABC","Vaccine":"Covax-22","Qty":"300","Origin":"Insurer-1","Destination":"Wholesaler-1","InsuredValue":1000,"Status":"In-Transit","TemperatureAlert":1,"CurrentLocation":"Wholesaler","GeoLocation":{"latitude":"16.9716°
                    S","xaxis":-16.9716,"longitude":"72.5946° W","yaxis":-72.5946,"location":"NJ"}},{"ShipmentID":"S-21","ShippingDate":"2020-11-03T03:48:11+0000","Insurer":"ABC
                    Insurer","PolicyId":"P-21","ClaimID":"CLM-P-21","ClaimRequestDate":"2020-11-03T04:15:07+0000","ClaimStatus":"New
                    claim request","Manufacturer":"ABC","Vaccine":"Covax-21","Qty":"250","Origin":"ABC1","Destination":"Retailer-3","InsuredValue":1200,"Status":"In-Transit","TemperatureAlert":1,"CurrentLocation":"Wholesaler","GeoLocation":{"latitude":"14.9716°
                    S","xaxis":-14.9716,"longitude":"69.5946° W","yaxis":-69.5946,"location":"NJ"}},{"ShipmentID":"S-20","ShippingDate":"2020-10-22T11:25:57+0000","Insurer":"ABC
                    Insurer","PolicyId":"P-20","ClaimID":"CLM-P-20","ClaimRequestDate":"2020-10-22T11:32:53+0000","ClaimStatus":"New
                    claim request","Manufacturer":"ABC Manufacturer","Vaccine":"Covax-19","Qty":"250","Origin":"ABC
                    Manufacturer","Destination":"ABC Wholesaler","InsuredValue":120,"Status":"In-Transit","TemperatureAlert":57,"CurrentLocation":"Manufacturer","GeoLocation":{"latitude":"14.9716° S","xaxis":-14.9716,"longitude":"69.5946° W","yaxis":-69.5946,"location":"NJ"}}]'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/deliver/shipment:
    put:
      description: API used to deliver shipment to consignee
      operationId: v12ColdchainVaccineboxDeliverShipmentPUT
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_3'
            examples:
              "0":
                value: "\t\t{\n\t\t\t\"shipmentId\" : \"S-22\",\t\t\n            \"\
                  currentOwner\" :\"Insurer-1\",\t\n\t\t\t\"currentRole\": \"Manufacturer\"\
                  ,\n\t\t\t\"nextRole\": \"Logistics\",\n\t\t\t\t\"shipmentTrackerEvent\"\
                  : {\n\t\t\t\t\"eventType\": \"SHIPMENT_DELIVERED\",\n\t\t\t\t\"\
                  eventDesc\": \"Pending Confirmation\"\t\t\t\n\t\t\t}  \t\t\t\n\t\
                  \t}\t\t\t"
              "1":
                value: "\t\t{\n\t\t\t\"shipmentId\" : \"S-22\",\t\t\n            \"\
                  currentOwner\" :\"Logistics-1\",\t\n\t\t\t\"currentRole\": \"Logistics\"\
                  ,\n\t\t\t\"nextRole\": \"Wholesaler\",\n\t\t\t\t\"shipmentTrackerEvent\"\
                  : {\n\t\t\t\t\"eventType\": \"SHIPMENT_DELIVERED\",\n\t\t\t\t\"\
                  eventDesc\": \"Pending Confirmation\"\t\t\t\n\t\t\t}  \t\t\t\n\t\
                  \t}"
      responses:
        "201":
          description: API used to deliver shipment to consignee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
              examples:
                "0":
                  value: '{"shipmentId":"S-22","currentRole":"Manufacturer","nextRole":"Logistics","response":"Pending
                    Confirmation"}'
                "1":
                  value: '{"shipmentId":"S-22","currentRole":"Logistics","nextRole":"Wholesaler","response":"Pending
                    Confirmation"}'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/simulateSensorData:
    post:
      description: API used to send simulated sensor data
      operationId: v12ColdchainVaccineboxSimulateSensorDataPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_4'
            examples:
              "0":
                value: "\t\t\t{\n\t\t\t\t\"shipmentId\": \"S-22\",\t\t\n\t\t\t\t\"\
                  deviceId\": \"D-22\",\t\n\t\t\t\t\"telemetry\": {\n\t\t\t\t\t\"\
                  temp\": -6,\n \t\t\t\t\t\"latitude\": \"16.9716° S\",\n\t\t\t\t\t\
                  \"longitude\": \"72.5946° W\",\n                    \"location\"\
                  : \"NJ\"                    \n \t\t\t\t}  \t\t\t\n\t\t\t}"
      responses:
        "200":
          description: Simulated sensor data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
              examples:
                "0":
                  value: '{"shipmentId":"S-22","deviceId":"D-22","response":-6}'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/shipment/S-22:
    get:
      description: API returns details of a specified shipment
      operationId: v12ColdchainVaccineboxShipmentS_22GET
      responses:
        "200":
          description: Shipment details response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_7'
              examples:
                "0":
                  value: '{"vaccineName":"Covax-22","shipmentId":"S-22","quantity":"300","shippingDate":"2020-11-03T05:36:57+0000","temperatureExcursion":0,"humidityRangeViolation":0,"manufacturer":"ABC","currentRole":"Manufacturer","currentOwner":"ABC
                    Manufacturer","status":"In-Transit","policyId":"P-21","insurer":"Insurer-1","insuredValue":1000,"claimId":"NC","claimStatus":"NA","claimRequestDate":"NA","shipmentTrackerEvents":[{"eventOwner":"ABC
                    Manufacturer","eventRole":"Manufacturer","eventType":"SHIPPING","eventDesc":"Left
                    Facility","sensorCondition":"Active, normal readings","eventDate":"2020-11-03T05:36:57+0000"}],"wayBill":{"origin":"Insurer-1","originRole":"Manufacturer","originAddress":"1567
                    TX  302, Dallas, TX 75204-2426, US","destination":"Wholesaler-1","destinationRole":"Wholesaler","destinationAddress":"Wholesaler-1,
                    Victoria Street, DH","logistics":"Logistics-1"},"currentGeoLocation":{"latitude":"12.9716°
                    N","xaxis":12.9716,"longitude":"77.5946° E","yaxis":77.5946,"location":"CA"},"batchId":"LNQEOL2RUONIWYJSGWCJZA"}'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/recentShipments:
    get:
      description: API returns recent shipment list
      operationId: v12ColdchainVaccineboxRecentShipmentsGET
      responses:
        "200":
          description: Recent shipment list
          content:
            application/json:
              schema:
                type: object
                properties: {}
                example: {}
                x-content-type: application/json
              examples:
                "0":
                  value: '["S-22","S-21","S-20","S-16","S-15"]'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/receive/shipment:
    put:
      description: API for receiving shipment by a consignee
      operationId: v12ColdchainVaccineboxReceiveShipmentPUT
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_5'
            examples:
              "0":
                value: "\t\t\t\t\t{\n\t\t\t\t\t\t\"shipmentId\" : \"S-22\",\n\t\t\t\
                  \t\t\t\"currentOwner\" :\"Logistics-1\",           \t\t\t\n\t\t\t\
                  \t\t\t\"currentRole\": \"Logistics\",\n\t\t\t\t\t\t\"nextRole\"\
                  : \"Wholesaler\",\n\t\t\t\t\t\t\t\"shipmentTrackerEvent\": {\n\t\
                  \t\t\t\t\t\t\"eventType\": \"SHIPMENT_RECEIVED\",\n\t\t\t\t\t\t\t\
                  \"eventDesc\": \"Received\"\t\t\t\n\t\t\t\t\t\t}  \t\t\t\n\t\t\t\
                  \t\t}\t\t"
              "1":
                value: "\t\t\t\t\t{\n\t\t\t\t\t\t\"shipmentId\" : \"S-22\",\n\t\t\t\
                  \t\t\t\"currentOwner\" :\"Wholesaler-1\",           \t\t\t\n\t\t\
                  \t\t\t\t\"currentRole\": \"Wholesaler\",\n\t\t\t\t\t\t\"nextRole\"\
                  : \"NA\",\n\t\t\t\t\t\t\t\"shipmentTrackerEvent\": {\n\t\t\t\t\t\
                  \t\t\"eventType\": \"SHIPMENT_RECEIVED\",\n\t\t\t\t\t\t\t\"eventDesc\"\
                  : \"Received\"\t\t\t\n\t\t\t\t\t\t}  \t\t\t\n\t\t\t\t\t}"
      responses:
        "201":
          description: Receive shipment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
              examples:
                "0":
                  value: '{"shipmentId":"S-22","currentRole":"Logistics","nextRole":"Wholesaler","response":"Received"}'
                "1":
                  value: '{"shipmentId":"S-22","currentRole":"Wholesaler","nextRole":"NA","response":"Received"}'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/highRiskShipments:
    get:
      description: API returns a list of high risk shipments
      operationId: v12ColdchainVaccineboxHighRiskShipmentsGET
      responses:
        "200":
          description: High risk shipments
          content:
            application/json:
              schema:
                type: object
                properties: {}
                example: {}
                x-content-type: application/json
              examples:
                "0":
                  value: '[{"ShipmentID":"S-20","ShippingDate":"2020-10-22T11:25:57+0000","PolicyId":"P-20","ClaimID":"CLM-P-20","ClaimRequestDate":"2020-10-22T11:32:53+0000","ClaimStatus":"New
                    claim request","Manufacturer":"ABC Manufacturer","Vaccine":"Covax-19","Qty":"250","Origin":"ABC
                    Manufacturer","Destination":"ABC Wholesaler","InsuredValue":120,"Status":"In-Transit","TemperatureAlert":57,"CurrentLocation":"Manufacturer"},{"ShipmentID":"S-16","ShippingDate":"2020-10-22T04:51:47+0000","PolicyId":"P-16","ClaimID":"NC","ClaimRequestDate":"NA","ClaimStatus":"NA","Manufacturer":"ABC
                    Manufacturer","Vaccine":"Covax-19","Qty":"250","Origin":"ABC Manufacturer","Destination":"ABC
                    Wholesaler","InsuredValue":160,"Status":"In-Transit","TemperatureAlert":12,"CurrentLocation":"Manufacturer"},{"ShipmentID":"S-15","ShippingDate":"2020-10-21T17:35:35+0000","PolicyId":"P-15","ClaimID":"NC","ClaimRequestDate":"NA","ClaimStatus":"NA","Manufacturer":"ABC
                    Manufacturer","Vaccine":"Covax-19","Qty":"250","Origin":"ABC Manufacturer","Destination":"ABC
                    Wholesaler","InsuredValue":150,"Status":"In-Transit","TemperatureAlert":7,"CurrentLocation":"Manufacturer"},{"ShipmentID":"S-07","ShippingDate":"2020-10-16T04:34:17+0000","PolicyId":"P-07","ClaimID":"CLM-P-07","ClaimRequestDate":"2020-10-16T04:47:25+0000","ClaimStatus":"New
                    claim request","Manufacturer":"Pfizer","Vaccine":"Covax-19","Qty":"200","InsuredValue":3200,"Status":"In-Transit","TemperatureAlert":23,"CurrentLocation":"Logistics"},{"ShipmentID":"S-06","ShippingDate":"2020-10-15T17:59:21+0000","PolicyId":"P-06","ClaimID":"CLM-P-06","ClaimRequestDate":"2020-10-15T17:59:40+0000","ClaimStatus":"New
                    claim request","Manufacturer":"Pfizer","Vaccine":"Covax-19","Qty":"50","InsuredValue":100,"Status":"In-Transit","TemperatureAlert":343,"CurrentLocation":"Manufacturer"},{"ShipmentID":"S-05","ShippingDate":"2020-10-15T17:59:03+0000","PolicyId":"P-05","ClaimID":"NC","ClaimRequestDate":"NA","ClaimStatus":"NA","Manufacturer":"Pfizer","Vaccine":"Covax-19","Qty":"250","InsuredValue":600,"Status":"In-Transit","TemperatureAlert":39,"CurrentLocation":"Manufacturer"},{"ShipmentID":"S-04","ShippingDate":"2020-10-15T17:48:56+0000","PolicyId":"P-04","ClaimID":"NC","ClaimRequestDate":"NA","ClaimStatus":"NA","Manufacturer":"Pfizer","Vaccine":"Covax-19","Qty":"150","InsuredValue":800,"Status":"In-Transit","TemperatureAlert":4,"CurrentLocation":"Manufacturer"},{"ShipmentID":"S-02","ShippingDate":"2020-10-15T17:48:07+0000","PolicyId":"P-02","ClaimID":"NC","ClaimRequestDate":"NA","ClaimStatus":"NA","Manufacturer":"Pfizer","Vaccine":"Covax-19","Qty":"250","InsuredValue":2500,"Status":"In-Transit","TemperatureAlert":3,"CurrentLocation":"Manufacturer"}]'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
  /v12/coldchain/vaccinebox/notifyHighRiskShipments:
    get:
      description: API used to notify high risk shipments
      operationId: v12ColdchainVaccineboxNotifyHighRiskShipmentsGET
      responses:
        "200":
          description: Notify high risk shipments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_8'
              examples:
                "0":
                  value: '{"HighRisk":8}'
      servers:
      - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
      x-swagger-router-controller: Default
    servers:
    - url: https://wh4cs2rdj6.execute-api.us-east-1.amazonaws.com
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        ClaimCount:
          type: integer
      example:
        ClaimCount: 0
    body:
      type: object
      properties:
        policyId:
          type: string
        shipmentId:
          type: string
    inline_response_200_1:
      type: object
      properties:
        ShipmentId:
          type: string
        ClaimId:
          type: string
        response:
          type: string
      example:
        ShipmentId: ShipmentId
        ClaimId: ClaimId
        response: response
    inline_response_200_2:
      type: object
      properties:
        Childlegs:
          type: array
          items:
            type: object
            properties:
              Origin:
                type: string
              MasterShipmentId:
                type: string
              destinationAddress:
                type: string
              RetailShipmentId:
                type: string
              destinationRole:
                type: string
              originAddress:
                type: string
              destination:
                type: string
              originRole:
                type: string
              RetailQuantity:
                type: integer
              Logistics:
                type: string
            example:
              Origin: Origin
              MasterShipmentId: MasterShipmentId
              destinationAddress: destinationAddress
              RetailShipmentId: RetailShipmentId
              destinationRole: destinationRole
              originAddress: originAddress
              destination: destination
              originRole: originRole
              RetailQuantity: 0
              Logistics: Logistics
        OriginLeg:
          type: object
          properties:
            ShipmentId:
              type: string
            Origin:
              type: string
            destinationAddress:
              type: string
            destinationRole:
              type: string
            DeviceId:
              type: string
            originAddress:
              type: string
            BatchId:
              type: string
            destination:
              type: string
            originRole:
              type: string
            Logistics:
              type: string
          example:
            ShipmentId: ShipmentId
            Origin: Origin
            destinationAddress: destinationAddress
            destinationRole: destinationRole
            DeviceId: DeviceId
            originAddress: originAddress
            BatchId: BatchId
            destination: destination
            originRole: originRole
            Logistics: Logistics
      example:
        Childlegs:
        - Origin: Origin
          MasterShipmentId: MasterShipmentId
          destinationAddress: destinationAddress
          RetailShipmentId: RetailShipmentId
          destinationRole: destinationRole
          originAddress: originAddress
          destination: destination
          originRole: originRole
          RetailQuantity: 0
          Logistics: Logistics
        - Origin: Origin
          MasterShipmentId: MasterShipmentId
          destinationAddress: destinationAddress
          RetailShipmentId: RetailShipmentId
          destinationRole: destinationRole
          originAddress: originAddress
          destination: destination
          originRole: originRole
          RetailQuantity: 0
          Logistics: Logistics
        OriginLeg:
          ShipmentId: ShipmentId
          Origin: Origin
          destinationAddress: destinationAddress
          destinationRole: destinationRole
          DeviceId: DeviceId
          originAddress: originAddress
          BatchId: BatchId
          destination: destination
          originRole: originRole
          Logistics: Logistics
    inline_response_200_3:
      type: object
      properties:
        txTime:
          type: string
        shipmentId:
          type: string
        temperature:
          type: integer
        deviceId:
          type: string
      example:
        txTime: txTime
        shipmentId: shipmentId
        temperature: 0
        deviceId: deviceId
    v12coldchainvaccineboxretailShipment_WayBill:
      type: object
      properties:
        destinationAddress:
          type: string
        destinationRole:
          type: string
        originAddress:
          type: string
        origin:
          type: string
        destination:
          type: string
        logistics:
          type: string
        originRole:
          type: string
    body_1:
      type: object
      properties:
        MasterShipmentId:
          type: string
        RetailShipmentId:
          type: string
        WayBill:
          $ref: '#/components/schemas/v12coldchainvaccineboxretailShipment_WayBill'
        RetailQuantity:
          type: integer
    inline_response_200_4:
      type: object
      properties:
        RetailShipmentId:
          type: string
        shippingDate:
          type: string
        WayBill:
          type: object
          properties:
            destinationAddress:
              type: string
            destinationRole:
              type: string
            originAddress:
              type: string
            origin:
              type: string
            destination:
              type: string
            logistics:
              type: string
            originRole:
              type: string
          example:
            destinationAddress: destinationAddress
            destinationRole: destinationRole
            originAddress: originAddress
            origin: origin
            destination: destination
            logistics: logistics
            originRole: originRole
        RetailQuantity:
          type: integer
        status:
          type: string
      example:
        RetailShipmentId: RetailShipmentId
        shippingDate: shippingDate
        WayBill:
          destinationAddress: destinationAddress
          destinationRole: destinationRole
          originAddress: originAddress
          origin: origin
          destination: destination
          logistics: logistics
          originRole: originRole
        RetailQuantity: 0
        status: status
    body_2:
      type: object
      properties:
        vaccineName:
          type: string
        wayBill:
          $ref: '#/components/schemas/v12coldchainvaccineboxretailShipment_WayBill'
        quantity:
          type: string
        policyId:
          type: string
        shipmentId:
          type: string
        insurer:
          type: string
        insuredValue:
          type: integer
    inline_response_200_5:
      type: object
      properties:
        vaccineName:
          type: string
        wayBill:
          type: object
          properties:
            destinationAddress:
              type: string
            destinationRole:
              type: string
            originAddress:
              type: string
            origin:
              type: string
            destination:
              type: string
            logistics:
              type: string
            originRole:
              type: string
          example:
            destinationAddress: destinationAddress
            destinationRole: destinationRole
            originAddress: originAddress
            origin: origin
            destination: destination
            logistics: logistics
            originRole: originRole
        quantity:
          type: string
        insuredValue:
          type: integer
        shipmentTrackerEvent:
          type: array
          items:
            type: object
            properties:
              eventDesc:
                type: string
              eventOwner:
                type: string
              sensorCondition:
                type: string
              eventType:
                type: string
              eventRole:
                type: string
              eventDate:
                type: string
            example:
              eventDesc: eventDesc
              eventOwner: eventOwner
              sensorCondition: sensorCondition
              eventType: eventType
              eventRole: eventRole
              eventDate: eventDate
        batchId:
          type: string
        currentGeoLocation:
          type: object
          properties:
            xaxis:
              type: number
            latitude:
              type: string
            location:
              type: string
            yaxis:
              type: number
            longitude:
              type: string
          example:
            xaxis: 6.02745618307040320615897144307382404804229736328125
            latitude: latitude
            location: location
            yaxis: 1.46581298050294517310021547018550336360931396484375
            longitude: longitude
        manufacturer:
          type: string
        policyId:
          type: string
        shipmentId:
          type: string
        insurer:
          type: string
        currentOwner:
          type: string
        currentRole:
          type: string
        temperatureExcursion:
          type: integer
        status:
          type: string
        humidityRangeViolation:
          type: integer
      example:
        vaccineName: vaccineName
        wayBill:
          destinationAddress: destinationAddress
          destinationRole: destinationRole
          originAddress: originAddress
          origin: origin
          destination: destination
          logistics: logistics
          originRole: originRole
        quantity: quantity
        insuredValue: 0
        shipmentTrackerEvent:
        - eventDesc: eventDesc
          eventOwner: eventOwner
          sensorCondition: sensorCondition
          eventType: eventType
          eventRole: eventRole
          eventDate: eventDate
        - eventDesc: eventDesc
          eventOwner: eventOwner
          sensorCondition: sensorCondition
          eventType: eventType
          eventRole: eventRole
          eventDate: eventDate
        batchId: batchId
        currentGeoLocation:
          xaxis: 6.02745618307040320615897144307382404804229736328125
          latitude: latitude
          location: location
          yaxis: 1.46581298050294517310021547018550336360931396484375
          longitude: longitude
        manufacturer: manufacturer
        policyId: policyId
        shipmentId: shipmentId
        insurer: insurer
        currentOwner: currentOwner
        currentRole: currentRole
        temperatureExcursion: 5
        status: status
        humidityRangeViolation: 5
    v12coldchainvaccineboxdelivershipment_shipmentTrackerEvent:
      type: object
      properties:
        eventDesc:
          type: string
        eventType:
          type: string
    body_3:
      type: object
      properties:
        shipmentId:
          type: string
        currentOwner:
          type: string
        shipmentTrackerEvent:
          $ref: '#/components/schemas/v12coldchainvaccineboxdelivershipment_shipmentTrackerEvent'
        currentRole:
          type: string
        nextRole:
          type: string
    inline_response_201:
      type: object
      properties:
        shipmentId:
          type: string
        response:
          type: string
        currentRole:
          type: string
        nextRole:
          type: string
      example:
        shipmentId: shipmentId
        response: response
        currentRole: currentRole
        nextRole: nextRole
    v12coldchainvaccineboxsimulateSensorData_telemetry:
      type: object
      properties:
        temp:
          type: integer
        latitude:
          type: string
        location:
          type: string
        longitude:
          type: string
    body_4:
      type: object
      properties:
        shipmentId:
          type: string
        telemetry:
          $ref: '#/components/schemas/v12coldchainvaccineboxsimulateSensorData_telemetry'
        deviceId:
          type: string
    inline_response_200_6:
      type: object
      properties:
        shipmentId:
          type: string
        response:
          type: integer
        deviceId:
          type: string
      example:
        shipmentId: shipmentId
        response: 0
        deviceId: deviceId
    inline_response_200_7:
      type: object
      properties:
        vaccineName:
          type: string
        wayBill:
          type: object
          properties:
            destinationAddress:
              type: string
            destinationRole:
              type: string
            originAddress:
              type: string
            origin:
              type: string
            destination:
              type: string
            logistics:
              type: string
            originRole:
              type: string
          example:
            destinationAddress: destinationAddress
            destinationRole: destinationRole
            originAddress: originAddress
            origin: origin
            destination: destination
            logistics: logistics
            originRole: originRole
        quantity:
          type: string
        shippingDate:
          type: string
        insuredValue:
          type: integer
        shipmentTrackerEvents:
          type: array
          items:
            type: object
            properties:
              eventDesc:
                type: string
              eventOwner:
                type: string
              sensorCondition:
                type: string
              eventType:
                type: string
              eventRole:
                type: string
              eventDate:
                type: string
            example:
              eventDesc: eventDesc
              eventOwner: eventOwner
              sensorCondition: sensorCondition
              eventType: eventType
              eventRole: eventRole
              eventDate: eventDate
        claimId:
          type: string
        batchId:
          type: string
        currentGeoLocation:
          type: object
          properties:
            xaxis:
              type: number
            latitude:
              type: string
            location:
              type: string
            yaxis:
              type: number
            longitude:
              type: string
          example:
            xaxis: 6.02745618307040320615897144307382404804229736328125
            latitude: latitude
            location: location
            yaxis: 1.46581298050294517310021547018550336360931396484375
            longitude: longitude
        manufacturer:
          type: string
        claimRequestDate:
          type: string
        policyId:
          type: string
        shipmentId:
          type: string
        insurer:
          type: string
        currentOwner:
          type: string
        currentRole:
          type: string
        temperatureExcursion:
          type: integer
        claimStatus:
          type: string
        humidityRangeViolation:
          type: integer
        status:
          type: string
      example:
        vaccineName: vaccineName
        wayBill:
          destinationAddress: destinationAddress
          destinationRole: destinationRole
          originAddress: originAddress
          origin: origin
          destination: destination
          logistics: logistics
          originRole: originRole
        quantity: quantity
        shippingDate: shippingDate
        insuredValue: 0
        shipmentTrackerEvents:
        - eventDesc: eventDesc
          eventOwner: eventOwner
          sensorCondition: sensorCondition
          eventType: eventType
          eventRole: eventRole
          eventDate: eventDate
        - eventDesc: eventDesc
          eventOwner: eventOwner
          sensorCondition: sensorCondition
          eventType: eventType
          eventRole: eventRole
          eventDate: eventDate
        claimId: claimId
        batchId: batchId
        currentGeoLocation:
          xaxis: 6.02745618307040320615897144307382404804229736328125
          latitude: latitude
          location: location
          yaxis: 1.46581298050294517310021547018550336360931396484375
          longitude: longitude
        manufacturer: manufacturer
        claimRequestDate: claimRequestDate
        policyId: policyId
        shipmentId: shipmentId
        insurer: insurer
        currentOwner: currentOwner
        currentRole: currentRole
        temperatureExcursion: 5
        claimStatus: claimStatus
        humidityRangeViolation: 5
        status: status
    body_5:
      type: object
      properties:
        shipmentId:
          type: string
        currentOwner:
          type: string
        shipmentTrackerEvent:
          $ref: '#/components/schemas/v12coldchainvaccineboxdelivershipment_shipmentTrackerEvent'
        currentRole:
          type: string
        nextRole:
          type: string
    inline_response_200_8:
      type: object
      properties:
        HighRisk:
          type: integer
      example:
        HighRisk: 0
